/// Generated by scripts/gnfp_version.py from git rev-list --count HEAD.
library;
const String kGnfpPackageVersion = '0.1.9';
const int kGnfpCommitCount = 19;
const String kGnfpCoreWalletTitlePrefix = '\$GNFP core wallet v';

String gnfpCoreWalletTitle([String version = kGnfpPackageVersion]) =>
    '$kGnfpCoreWalletTitlePrefix$version';
