/// Generated by scripts/gnfp_version.py from git rev-list --count HEAD.
library;
const String kGnfpPackageVersion = '0.2.1';
const int kGnfpCommitCount = 21;
const String kGnfpCoreWalletTitlePrefix = '\$GNFP core wallet v';

String gnfpCoreWalletTitle([String version = kGnfpPackageVersion]) =>
    '$kGnfpCoreWalletTitlePrefix$version';
